local lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/Whiteknight-Bank/By-BankZy/refs/heads/main/Ui_Lib.lua/Boltlib.lua"))()
local win = lib:CreateWindow("💎 Bank Hub 💎")

win:Label("ระบบหลัก")
win:Toggle("Auto Claim Expertise", function(on)
    print("Toggle:", on)
end)
win:Button("Button", function()
    print("ปุ่มถูกกดแล้ว!")
end)
